name: Clima Diario

on:
  schedule:
    - cron: '0 9 * * *'  # Ejecutar todos los días a las 9:00 UTC
  workflow_dispatch:     # Permite ejecutarlo manualmente desde GitHub

jobs:
  clima:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo .env
        run: |
          echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" > .env

      - name: Ejecutar script
        run: |
          python src/fetch_all_weather.py

      - name: Subir cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/datos_clima_argentina.csv
          git commit -m "Actualizar datos clima diaria [bot]" || echo "Sin cambios"
          git push
