name: Clima Diario a BigQuery

on:
  schedule:
    - cron: '0 10 * * *'  # Corre todos los días a las 10:00 UTC (7:00 Argentina)
  workflow_dispatch:      # Permite correrlo manualmente desde GitHub

jobs:
  subir-a-bigquery:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo de credenciales GCP
        run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > gcp_key.json
          

      - name: Setear GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json" >> $GITHUB_ENV

      - name: Ejecutar script para obtener clima
        run: python src/fetch_all_weather.py

      - name: Ejecutar script de carga a BigQuery
        run: python src/upload_to_bigquery.py
